update 5.8

diff --git a/drivers/infiniband/ulp/srp/debian/srp-dkms.postinst b/drivers/infiniband/ulp/srp/debian/srp-dkms.postinst
--- a/drivers/infiniband/ulp/srp/debian/srp-dkms.postinst
+++ b/drivers/infiniband/ulp/srp/debian/srp-dkms.postinst
@@ -2,29 +2,51 @@
 set -e
 
 # Get the package version
-package=srp
-version=`dpkg-query -W -f='${Version}' "$package-dkms" \
-    | sed -e 's/[+-].*//'`
+NAME=srp
+PACKAGE_NAME=$NAME-dkms
+CVERSION=`dpkg-query -W -f='${Version}' $PACKAGE_NAME | awk -F "-" '{print $1}' | cut -d\: -f2`
+ARCH=`uname -m`
 
-isadded=`dkms status -m "$name" -v "$version"`
+dkms_configure () {
+	POSTINST="/usr/src/$NAME-$CVERSION/common.postinst"
+	if [ -f "$POSTINST" ]; then
+		"$POSTINST" "$NAME" "$CVERSION" "/usr/share/$PACKAGE_NAME" "$ARCH" "$2"
+		return $?
+	fi
+	echo "WARNING: $POSTINST does not exist." >&2
+	echo "ERROR: DKMS version is too old and $PACKAGE_NAME was not" >&2
+	echo "built with legacy DKMS support." >&2
+	echo "You must either rebuild $PACKAGE_NAME with legacy postinst" >&2
+	echo "support or upgrade DKMS to a more current version." >&2
+	return 1
+}
 
-if [ "x${isadded}" = "x" ] ; then
-    dkms add -m "$package" -v "$version"
-fi
+case "$1" in
+	configure)
+		dkms_configure
+	;;
 
-if [ "$1" = 'configure' ] ; then
-    dkms build -m "$package" -v "$version" && dkms install -m "$package" -v "$version" --force || true
-fi
+	abort-upgrade|abort-remove|abort-deconfigure)
+	;;
+
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+	;;
+esac
 
 # update openib.conf
 init_conf_file=/etc/infiniband/openib.conf
 if [ -e $init_conf_file ] &&
-		! grep -q 'SRP_LOAD=' $init_conf_file; then
-	cat <<EOF >>$init_conf_file
+               ! grep -q 'SRP_LOAD=' $init_conf_file; then
+       cat <<EOF >>$init_conf_file
 # Load SRP module
 SRP_LOAD=no
 EOF
 fi
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
